# /// script
# dependencies = [
#   "data-designer"
# ]
# ///
import data_designer.config as dd
import random

@dd.custom_column_generator(
    required_columns=["person"],
    side_effect_columns=["Location", "Age"],
)
def extract_person_fields(row: dict) -> dict:
    """Extract fields from the person object generated by Faker/Nemotron."""
    person = row["person"]
    # person is a dict with fields like 'first_name', 'last_name', 'city', 'state', 'age'
    # Fallback to random if fields are missing depending on the Faker version
    city = person.get("city", "Unknown")
    state = person.get("state", "Unknown")
    row["person_fields"] = True
    row["Location"] = f"{city}, {state}"
    row["Age"] = person.get("age", random.randint(18, 80))
    return row

def load_config_builder() -> dd.DataDesignerConfigBuilder:
    config_builder = dd.DataDesignerConfigBuilder()

    # User ID
    config_builder.add_column(
        dd.SamplerColumnConfig(
            name="User-ID",
            sampler_type=dd.SamplerType.UUID,
            params=dd.UUIDSamplerParams(short_form=True)
        )
    )

    # Person sampling using Faker for varied realistic names and locations
    config_builder.add_column(
        dd.SamplerColumnConfig(
            name="person",
            sampler_type=dd.SamplerType.PERSON_FROM_FAKER,
            params=dd.PersonFromFakerSamplerParams(
                locale="fr_FR",
                age_range=[15, 85]
            ),
            drop=True # Only keep the derived columns
        )
    )

    config_builder.add_column(
        dd.CustomColumnConfig(
            name="person_fields",
            generator_function=extract_person_fields
        )
    )

    return config_builder
